spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/catmart_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: catmart_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info
