spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/catmart_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: catmart_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


uploadPath: file:///C:/catmart-upload/
categoryImgLocation: C:/catmart-upload/category
productImgLocation: C:/catmart-upload/product
